XGBoost:
  scale_pos_weight: 200
  max_depth: 5
  min_child_weight: 3
  subsample: 0.65
  colsample_bytree: 0.9
  objective: 'binary:logistic'
  eta: 0.005
  gamma: 0.1
  n_estimators: 1000 
  enable_categorical: True
  eval_metric: 'auc'
  alpha: 0.05
 