COLUMNS:
  ACC_NO: int64
  MIN_DUE_AMT_1: float64
  MIN_DUE_AMT_2: float64
  MIN_DUE_AMT_3: float64
  MIN_DUE_AMT_4: float64
  MIN_DUE_AMT_5: float64
  MIN_DUE_AMT_6: float64
  TOT_SPEND_AMT_1: float64
  TOT_SPEND_AMT_2: float64
  TOT_SPEND_AMT_3: float64
  TOT_SPEND_AMT_4: float64
  TOT_SPEND_AMT_5: float64
  TOT_SPEND_AMT_6: float64
  PAYMENT_AMT_1: float64
  PAYMENT_AMT_2: float64
  PAYMENT_AMT_3: float64
  PAYMENT_AMT_4: float64
  PAYMENT_AMT_5: float64
  PAYMENT_AMT_6: float64
  FINAL_LIMIT: int64
  AGE: int64
  MONTH_END_BAL_LCY: float64
  REV_SETT_1_REVOLVER: int64
  REV_SETT_1_SETTLER: int64
  REV_SETT_2_REVOLVER: int64
  REV_SETT_2_SETTLER: int64
  REV_SETT_3_REVOLVER: int64
  REV_SETT_3_SETTLER: int64
  REV_SETT_4_REVOLVER: int64
  REV_SETT_4_SETTLER: int64
  REV_SETT_5_REVOLVER: int64
  REV_SETT_5_SETTLER: int64
  REV_SETT_6_REVOLVER: int64
  REV_SETT_6_SETTLER: int64
  RESTRUCTURED_PLAN_N: int64
  RESTRUCTURED_PLAN_Y: int64
  ST_GENERAL_ACC_BLCK: int64
  ST_GENERAL_ACC_CLST: int64
  ST_GENERAL_ACC_DACL: int64
  ST_GENERAL_ACC_DCBK: int64
  ST_GENERAL_ACC_DLNQ: int64
  ST_GENERAL_ACC_DRSP: int64
  ST_GENERAL_ACC_NORM: int64
  ST_GENERAL_ACC_PCLS: int64
  ST_GENERAL_ACC_RCDF: int64
  ST_GENERAL_ACC_RCLS: int64
  ST_GENERAL_ACC_RCPM: int64
  ST_GENERAL_ACC_RCSM: int64
  ST_GENERAL_ACC_RCSS: int64
  ST_GENERAL_ACC_RSET: int64
  ST_GENERAL_ACC_SACC: int64
  ST_GENERAL_ACC_SETT: int64
  ST_GENERAL_ACC_TERM: int64
  ST_GENERAL_ACC_WROF: int64
  GENDER_F: int64
  GENDER_M: int64
  PRODUCT_P13635: int64
  PRODUCT_P2f44d: int64
  PRODUCT_P3c2a4: int64
  PRODUCT_P3dbc4: int64
  PRODUCT_P59e14: int64
  PRODUCT_P78a55: int64
  PRODUCT_P7fc9a: int64
  PRODUCT_P8f4b3: int64
  PRODUCT_Pacee4: int64
  PRODUCT_Pd9c22: int64
  PRODUCT_Pdbb26: int64
  PRODUCT_Pdc921: int64
  PRODUCT_Pf4d80: int64
  LATE_PAY_FEE: float64
  OVER_LIMIT_FEE: int64
  TOTAL_OS: float64
  SPENDING_MONTHS: int64
  PAYMENT_MONTHS: int64
  MONTHS_SINCE_LAST_SPEND: int64
  MONTHS_SINCE_LAST_PAY: int64
  MONTHS_SINCE_LAST_SETTLER: int64
  MONTHS_SINCE_LAST_REVOLVER: int64

TARGET_COLUMN:
  name: 3_MONTH_NPL_STATUS
