COLUMNS:
  ACC_NO: float64
  MIN_DUE_AMT_1: float64
  MIN_DUE_AMT_2: float64
  MIN_DUE_AMT_3: float64
  MIN_DUE_AMT_4: float64
  MIN_DUE_AMT_5: float64
  MIN_DUE_AMT_6: float64
  OVER_LIMIT_FEE_1: float64
  OVER_LIMIT_FEE_2: float64
  OVER_LIMIT_FEE_3: float64
  OVER_LIMIT_FEE_4: float64
  OVER_LIMIT_FEE_5: float64
  OVER_LIMIT_FEE_6: float64
  TOT_SPEND_AMT_1: float64
  TOT_SPEND_AMT_2: float64
  TOT_SPEND_AMT_3: float64
  TOT_SPEND_AMT_4: float64
  TOT_SPEND_AMT_5: float64
  TOT_SPEND_AMT_6: float64
  PAYMENT_AMT_1: float64
  PAYMENT_AMT_2: float64
  PAYMENT_AMT_3: float64
  PAYMENT_AMT_4: float64
  PAYMENT_AMT_5: float64
  PAYMENT_AMT_6: float64
  TOTAL_OS_1: float64
  TOTAL_OS_2: float64
  TOTAL_OS_3: float64
  TOTAL_OS_4: float64
  TOTAL_OS_5: float64
  TOTAL_OS_6: float64
  LATE_PAY_FEE_1: float64
  LATE_PAY_FEE_2: float64
  LATE_PAY_FEE_3: float64
  LATE_PAY_FEE_4: float64
  LATE_PAY_FEE_5: float64
  LATE_PAY_FEE_6: float64
  A_SCORE_VALUE: float64
  FINAL_LIMIT: float64
  AGE: float64
  MONTH_END_BAL_LCY: float64
  REV_SETT_1_REVOLVER: float64
  REV_SETT_1_SETTLER: float64
  REV_SETT_2_REVOLVER: float64
  REV_SETT_2_SETTLER: float64
  REV_SETT_3_REVOLVER: float64
  REV_SETT_3_SETTLER: float64
  REV_SETT_4_REVOLVER: float64
  REV_SETT_4_SETTLER: float64
  REV_SETT_5_REVOLVER: float64
  REV_SETT_5_SETTLER: float64
  REV_SETT_6_REVOLVER: float64
  REV_SETT_6_SETTLER: float64
  RESTRUCTURED_PLAN_N: float64
  RESTRUCTURED_PLAN_Y: float64
  ST_GENERAL_ACC_BLCK: float64
  ST_GENERAL_ACC_CLST: float64
  ST_GENERAL_ACC_DACL: float64
  ST_GENERAL_ACC_DCBK: float64
  ST_GENERAL_ACC_DLNQ: float64
  ST_GENERAL_ACC_DRSP: float64
  ST_GENERAL_ACC_NORM: float64
  ST_GENERAL_ACC_PCLS: float64
  ST_GENERAL_ACC_RCDF: float64
  ST_GENERAL_ACC_RCLS: float64
  ST_GENERAL_ACC_RCPM: float64
  ST_GENERAL_ACC_RCSM: float64
  ST_GENERAL_ACC_RCSS: float64
  ST_GENERAL_ACC_RSET: float64
  ST_GENERAL_ACC_SACC: float64
  ST_GENERAL_ACC_SETT: float64
  ST_GENERAL_ACC_TERM: float64
  ST_GENERAL_ACC_WROF: float64
  GENDER_F: float64
  GENDER_M: float64
  PRODUCT_P13635: float64
  PRODUCT_P2f44d: float64
  PRODUCT_P3c2a4: float64
  PRODUCT_P3dbc4: float64
  PRODUCT_P59e14: float64
  PRODUCT_P78a55: float64
  PRODUCT_P7fc9a: float64
  PRODUCT_P8f4b3: float64
  PRODUCT_Pacee4: float64
  PRODUCT_Pd9c22: float64
  PRODUCT_Pdbb26: float64
  PRODUCT_Pdc921: float64
  PRODUCT_Pf4d80: float64
  NATURE_OF_BUS_DESC_ADVERTISING: float64
  NATURE_OF_BUS_DESC_AIRLINE: float64
  NATURE_OF_BUS_DESC_ARMEDSERVICES: float64
  NATURE_OF_BUS_DESC_AUTOMOBILES: float64
  NATURE_OF_BUS_DESC_BANKING/FINANCE: float64
  NATURE_OF_BUS_DESC_COMMODITYBROKING: float64
  NATURE_OF_BUS_DESC_COMMUNICATIONS: float64
  NATURE_OF_BUS_DESC_CONGLOMERATE: float64
  NATURE_OF_BUS_DESC_CONSTRUCTION: float64
  NATURE_OF_BUS_DESC_FREIGHTFORWARDING/SHIPPING: float64
  NATURE_OF_BUS_DESC_GARMENTS: float64
  NATURE_OF_BUS_DESC_GOVERNMENT: float64
  NATURE_OF_BUS_DESC_HEALTHCARE: float64
  NATURE_OF_BUS_DESC_HOTEL: float64
  NATURE_OF_BUS_DESC_HOUSEWIFE: float64
  NATURE_OF_BUS_DESC_IMPORT/EXPORT: float64
  NATURE_OF_BUS_DESC_INFORMATIONTECHNOLOGY: float64
  NATURE_OF_BUS_DESC_INSURANCE: float64
  NATURE_OF_BUS_DESC_MANUFACTURING: float64
  NATURE_OF_BUS_DESC_MEDICAL: float64
  NATURE_OF_BUS_DESC_NGO/NPO/CHARITY: float64
  NATURE_OF_BUS_DESC_OTHER: float64
  NATURE_OF_BUS_DESC_PHARMACEUTICALS: float64
  NATURE_OF_BUS_DESC_PLANTATIONS: float64
  NATURE_OF_BUS_DESC_PROFESSIONALSERVICES: float64
  NATURE_OF_BUS_DESC_PUBLICUTILITY: float64
  NATURE_OF_BUS_DESC_PUBLICITY: float64
  NATURE_OF_BUS_DESC_SHAREBROKING: float64
  NATURE_OF_BUS_DESC_TELECOMMUNICATIONS: float64
  NATURE_OF_BUS_DESC_TRADING: float64
  NATURE_OF_BUS_DESC_TRAVEL: float64
  NATURE_OF_BUS_DESC_TRAVEL/AIRLINE: float64

TARGET_COLUMN:
  name: 3_MONTH_NPL_STATUS
