artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://raw.githubusercontent.com/dishan-nithi/CW/refs/heads/main/final_df.zip
  local_data_file: artifacts/data_ingestion/final_df.zip
  unzip_dir: artifacts/data_ingestion
  token: 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

data validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/final_df.csv
  status_file: artifacts/data_validation/status.txt

data transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/final_df.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib